version: '3.8'

services:
  app:
    image: ghcr.io/joshua2031/springboot-assignment-4-template:latest
    container_name: springboot-seminar
    ports:
      - "8080:8080"
    restart: unless-stopped

  mysql:
    image: mysql:8.4
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE: seminar2025
      MYSQL_USER: user
      MYSQL_PASSWORD: somepassword
