apiVersion: apps/v1
kind: Deployment
metadata:
  name: seminar-app
  labels:
    app: seminar-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: seminar-app
  template:
    metadata:
      labels:
        app: seminar-app
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: seminar-app
          image: ghcr.io/joshua2031/springboot-assignment-4-template:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/seminar2025?useSSL=false&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: password1234
            - name: SPRING_DATA_REDIS_HOST
              value: redis-master
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: seminar-app-service
spec:
  type: NodePort
  selector:
    app: seminar-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
